auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

limits_config:
  allow_structured_metadata: false  # Critical fix

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb  # Must be "tsdb" not "tsdb-shipper"
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h